name: 'dbt_divvy'
version: '1.0.0'
config-version: 2

# This must match the profile name we put in ~/.dbt/profiles.yml
profile: 'divvy_project' 

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_divvy:
    # This ensures everything in the staging folder is a view by default
    staging:
      +materialized: view
    # This ensures your final tables are materialized and partitioned
    marts:
      +materialized: table